# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NetGuardian
version: "0.0.1"
slug: netguardian
description: A Home Assistant Add-on to combine, control, monitor and manage the home routers or any network equipments.
url: "https://github.com/mentormaya/ha-addons/tree/main/netguardian"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
